server:
  port: 8082

spring:
  application:
    name: notification-service

  datasource:
    url: jdbc:postgresql://localhost:5432/banking
    username: banking
    password: banking
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    table: flyway_schema_history_notification_service
    baseline-on-migrate: true
    baseline-version: 1

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-service
      auto-offset-reset: earliest
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.minh.notification.consumer.event.TransactionCompletedEvent
    listener:
      missing-topics-fatal: false

app:
  kafka:
    topics:
      transaction-completed: transaction.completed
      transaction-completed-dlt: transaction.completed.DLT
