CREATE TABLE accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_no VARCHAR(50) NOT NULL,
    customer_name VARCHAR(255) NOT NULL,
    balance NUMERIC(19, 2) NOT NULL,
    currency VARCHAR(10) NOT NULL,
    status VARCHAR(50) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reference_no VARCHAR(100) NOT NULL,
    from_account_no VARCHAR(50) NOT NULL,
    to_account_no VARCHAR(50) NOT NULL,
    amount NUMERIC(19, 2) NOT NULL,
    currency VARCHAR(10) NOT NULL,
    type VARCHAR(50) NOT NULL,
    status VARCHAR(50) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE ledger_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_reference_no VARCHAR(100) NOT NULL,
    account_no VARCHAR(50) NOT NULL,
    entry_type VARCHAR(50) NOT NULL,
    amount NUMERIC(19, 2) NOT NULL,
    balance_after NUMERIC(19, 2) NOT NULL,
    description VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE UNIQUE INDEX uk_accounts_account_no ON accounts (account_no);
CREATE UNIQUE INDEX uk_transactions_reference_no ON transactions (reference_no);
CREATE INDEX idx_ledger_entries_account_no_created_at ON ledger_entries (account_no, created_at);
CREATE INDEX idx_transactions_created_at ON transactions (created_at);
CREATE INDEX idx_transactions_from_account_no ON transactions (from_account_no);
CREATE INDEX idx_transactions_to_account_no ON transactions (to_account_no);
