CREATE TABLE daily_transaction_summary (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    summary_date DATE NOT NULL,
    total_transfer_count BIGINT NOT NULL,
    total_transfer_amount NUMERIC(19, 2) NOT NULL,
    total_success_count BIGINT NOT NULL,
    total_failed_count BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE UNIQUE INDEX uk_daily_transaction_summary_summary_date
    ON daily_transaction_summary (summary_date);
