CREATE TABLE audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action VARCHAR(64) NOT NULL,
    resource_type VARCHAR(64) NOT NULL,
    resource_id VARCHAR(128),
    request_data TEXT,
    response_data TEXT,
    status VARCHAR(32) NOT NULL,
    error_message VARCHAR(1000),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_audit_logs_action_created_at ON audit_logs (action, created_at);
CREATE INDEX idx_audit_logs_resource_type_resource_id ON audit_logs (resource_type, resource_id);
